---
# For global lib configuration
MasterBuildVersion: "15.2.2.0"
MajorRelease: ''
MinorRelease: ''
# Steps default configuration
ResolveRepo: 'cd-passed-pl'
PromoteEnabled: true
InstallAction: 'both' #uninstall, install, both
DBInstallParams: 'ARPSYSTEMCOMPONENT=false,IMPACT360DATADIR=C:/Impact360/Data/,IMPACT360SOFTWAREDIR=C:/Impact360/Software/,SQLSERVERHOSTNAMECOMMON=consolidate,SQLSERVERPORTCOMMON=1433,IMSA_DOMAIN=consolidate,IMSA_NAME=ap2admin,IMSA_PASSWORD=verint1!,DMSA_DOMAIN=consolidate,DMSA_NAME=ap2admin,DMSA_PASSWORD=verint1!,INSTALLLANGUAGE=en_US,DATAFILESPATH=C:/Impact360/Databases,LOGFILESPATH=C:/Impact360/Databases,DBTYPE=WH,DBNAME=BPWAREHOUSEDB'
InstallVersion: '[RELEASE]'
SearchTags:
    Flavor: "green"

Components: # The Product Name just to give idea of what the GUI is, usely woudl be the same
    Framework Foundation:
        InstallationUnitGUID: '81F973AD-7284-4c36-9637-16EEA43337B4'
        InstallParams: ''
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    WFM Common:
        InstallationUnitGUID:  '452F6916-AA15-48b0-B4BF-63CD6EC78590'
        InstallParams: 'ARPSYSTEMCOMPONENT=false'
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    WFM Reporting:
        InstallationUnitGUID:  'a0dfe68e-59f1-4eac-8ff3-88638dc8bbf8'
        InstallParams: ''
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    Framework Integration Server:
        InstallationUnitGUID:  '4E693109-AB2D-41D8-A88D-1506E0D654B9'
        InstallParams: ''
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    Framework Warehouse Database:
        InstallationUnitGUID:  '621243F6-4743-4228-9364-574643D1CCE9'
        InstallParams: "${DBInstallParams}"
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    default:
        InstallationUnitGUID:  'Unknown'
        InstallParams: 'Unknown'
        InstallAction: "${InstallAction}"
        PromoteEnabled: false
        ResolveRepo: 'Unknown'
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"

...