---
# For global lib configuration
MasterBuildVersion: "15.2.2.0"
MajorRelease: ''
MinorRelease: ''
# Steps default configuration
ResolveRepo: 'cd-passed-pl'
PromoteEnabled: true
InstallAction: 'both' #uninstall, install, both
DBInstallParams: 'ARPSYSTEMCOMPONENT=false,IMPACT360DATADIR=C:/Impact360/Data/,IMPACT360SOFTWAREDIR=C:/Impact360/Software/,SQLSERVERHOSTNAMECOMMON=consolidate,SQLSERVERPORTCOMMON=1433,IMSA_DOMAIN=consolidate,IMSA_NAME=ap2admin,IMSA_PASSWORD=verint1!,DMSA_DOMAIN=consolidate,DMSA_NAME=ap2admin,DMSA_PASSWORD=verint1!,INSTALLLANGUAGE=en_US,DATAFILESPATH=C:/Impact360/Databases,LOGFILESPATH=C:/Impact360/Databases,DBTYPE=WH,DBNAME=BPWAREHOUSEDB'
InstallVersion: '[RELEASE]'
SearchTags:
    Flavor: "green"

Components: # The Product Name just to give idea of what the GUI is, usely woudl be the same
    Framework Foundation:
        InstallationUnitGUID: ''
        InstallParams: ''
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    WFM Common:
        InstallationUnitGUID:  ''
        InstallParams: 'ARPSYSTEMCOMPONENT=false'
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    WFM Reporting:
        InstallationUnitGUID:  ''
        InstallParams: ''
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    Framework Integration Server:
        InstallationUnitGUID:  ''
        InstallParams: ''
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    Framework Warehouse Database:
        InstallationUnitGUID:  ''
        InstallParams: "${DBInstallParams}"
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"
    default:
        InstallationUnitGUID:  ''
        InstallParams: ''
        InstallAction: "${InstallAction}"
        PromoteEnabled: "${PromoteEnabled}"
        ResolveRepo: "${ResolveRepo}"
        Version: "${InstallVersion}"
        SearchTags: "${SearchTags}"

...